version: '3.7'

services:
  charitable: &charitable
    build: &build
      context: .
      args:
        version: "5.6"
        charitable_version: "1.6.46"
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - /var/www/html
      - ./charitable-begateway:/var/www/html/wp-content/plugins/charitable-begateway
      - ./docker/src/languages:/var/www/html/wp-content/languages
    networks:
      - default
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: mysql

  mysql:
    image: mysql:5.6
    networks:
      - default
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
